---
- name: modprobe zfs
  command: modprobe zfs

# TODO: fail safe and revert
- name: reload nftables
  service:
    name: nftables
    state: reloaded
- name: restart nftables
  service:
    name: nftables
    state: restarted

- name: reload ulogd
  service:
    name: ulogd
    state: reloaded
